### PR TITLE
P506-012: Fix UnconstrainedArrayIndices.index_type

### PR DESCRIPTION
**Pull request by raph-amiard**

### CODE REVIEW

**Comment by pmderodat** [comment]
Looks like you forgot the fix for S709-005: the new testcase fails on Travis CI. Could you have a look?

**Comment by raph-amiard** [comment]
@pmderodat I think it's only because my branches were not named the same, and the fix is in Langkit. Restarting the travis !

**Comment by raph-amiard** [comment]
Actually the travis is passing now, didn't have to restart it :)

**Comment by pmderodat** [comment]
I see, thanks!

**Comment by pmderodat** [comment]
The Travis “passes” (it’s green), but if you have a look at the testsuite log there, you’ll see one failure :). I see in the log that there is no `topic/fix_index_type` branch in your Langkit fork, so that explains it.

**Pull request merged**
